### ISSUE TITLE
Server side device information tables

### ISSUE THREAD

**Issue by pgunasekara** [pgunasekara/4zp6#40]
Create the following tables to hold information about device state, and create endpoints to get and set this information. 

The android application will call **SetDeviceInfo** when the user updates information for a specific device (ie, assign it to a new user), or when it needs to set the last timestamp that the device was synced. **GetDeviceInfo** will be called for each individual device that the app scans and this will retrieve the user that it's assigned to, and the last time the device was synced.

**Tables**
_devices_
- id - mac address of the devices (should be unique) (or maybe the UUID of the device?) : string
- friendlyName - name for the device : string
- userId - id of the user that the sensor is assigned to : int
- lastSync - last time the device was synced with the app : DateTime

_users_
- id - auto increment, unique : int
- name - name of user : string
- avatar - profile picture for user : blob

**Endpoints**
_SetDeviceInfo_ - Updates the devices table
Input:
- id, newFriendlyName, newUserId, newLastSync (if any of these are null, except for Id, skip updating that field)

_GetDeviceInfo_ - Returns data from the devices table
Input:
- mac address

Output:
- device name, assigned user id, user avatar, last synced timestamp

**Comment by teovoinea** [comment]
Added in #72
